### ISSUE TITLE
Refresh of Page Visualization fails

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar-developer-tools-web-extension#3]
After editing the `widget.json` of a widget (e.g. the `format`) which resolves in changes at the page visualization tab, the extension doesn't refreshes the view correctly. The *laxar-developer-tools-widget* doesn't has this bug.

**Comment by x1B** [comment]
Should be re-evaluated for the current version before releasing v2.0.0

**Comment by x1B** [comment]
Possibly related: when browsing through thee flow of a LaxarJS multi-page application, there seem to be false alerts warning about duplicate event topics in the event display widget. I noticed this with LaxarJS runtime v1 (and it may actually be a bug there, not here). Not sure if it is still applicable to v2.

**Comment by x1B** [comment]
_Closing:_ This can no longer be reproduced.
